### ISSUE TITLE
Add a 2-pages example

### ISSUE THREAD

**Issue by NormandErwan** [NormandErwan/EffectiveCV#1]

**Comment by afiqaize** [comment]
Hey, I'm using your template and would find this to be very cool. When I tried introducing a \newpage and then adding another \cvcontent, the compilation complains with \endcsname and \rc@extract@page errors, but the page appeared and looks correct.

Any ideas what I'm doing wrong?

**Comment by NormandErwan** [comment]
Hello, thank you for your feedback! Glad other people are using this package!

I will try to reproduce and fix your issue.

**Comment by NormandErwan** [comment]
I haven't been able to reproduce your issue. I've added a second page (a74ea58) to [cv.tex](https://github.com/NormandErwan/EffectiveCV/blob/master/cv.tex).

Can you provide me an example of your code?

**Comment by afiqaize** [comment]
That's exactly what I did. Thanks to your hint I realized the problem had nothing to do with adding new pages.

It has to do with using \cvlink within a \cvitem and presumably their friends instead.

**Comment by NormandErwan** [comment]
Could you open a new issue? I'm closing this one.
